// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20251129213906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelos.Models.Cargo", b =>
                {
                    b.Property<int>("CargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CargoID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Modelos.Models.Carrera", b =>
                {
                    b.Property<int>("CarreraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarreraID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CarreraID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Modelos.Models.CartaGenerada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCarta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PlantillaId")
                        .HasColumnType("int");

                    b.Property<string>("RutaPDF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioPersonalID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaId");

                    b.HasIndex("UsuarioPersonalID");

                    b.ToTable("CartasGeneradas", t =>
                        {
                            t.HasCheckConstraint("CK_CartaGenerada_JSON", "ISJSON(Datos) = 1");
                        });
                });

            modelBuilder.Entity("Modelos.Models.CategoriaNecesidad", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasNecesidades");
                });

            modelBuilder.Entity("Modelos.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartamentoID");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Modelos.Models.DisciplinaArtistica", b =>
                {
                    b.Property<int>("DisciplinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplinaID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DisciplinaID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("DisciplinasArtisticas");
                });

            modelBuilder.Entity("Modelos.Models.EstadoUsuario", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosUsuarios");
                });

            modelBuilder.Entity("Modelos.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteID"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Carrera")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Disciplina")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Municipio")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("EstudianteID");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.HasIndex("Carrera");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Disciplina");

                    b.HasIndex("Municipio");

                    b.ToTable("Estudiantes", t =>
                        {
                            t.HasCheckConstraint("CK_Estudiante_Sexo", "Sexo IN ('M','F')");
                        });
                });

            modelBuilder.Entity("Modelos.Models.Evento", b =>
                {
                    b.Property<int>("EventoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFinal")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Salon")
                        .HasColumnType("int");

                    b.HasKey("EventoID");

                    b.HasIndex("Salon");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Modelos.Models.Municipio", b =>
                {
                    b.Property<int>("MunicipioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipioID"));

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MunicipioID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("Modelos.Models.NecesidadEvento", b =>
                {
                    b.Property<int>("NecesidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NecesidadID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubcategoriaID")
                        .HasColumnType("int");

                    b.HasKey("NecesidadID");

                    b.HasIndex("EventoID");

                    b.HasIndex("SubcategoriaID");

                    b.ToTable("NecesidadesEventos", t =>
                        {
                            t.HasCheckConstraint("CK_NecesidadEvento_Cantidad", "Cantidad > 0");
                        });
                });

            modelBuilder.Entity("Modelos.Models.Personal", b =>
                {
                    b.Property<int>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalID"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DireccionDomiciliaria")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Disciplina")
                        .HasColumnType("int");

                    b.Property<int>("Municipio")
                        .HasColumnType("int");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("PersonalID");

                    b.HasIndex("Cargo");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Disciplina");

                    b.HasIndex("Municipio");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.ToTable("Personal", t =>
                        {
                            t.HasCheckConstraint("CK_Personal_Sexo", "Sexo IN ('M','F')");
                        });
                });

            modelBuilder.Entity("Modelos.Models.PlantillaCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("PlantillasCartas");
                });

            modelBuilder.Entity("Modelos.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorID"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GradoAcademico")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProfesorID");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Modelos.Models.Salon", b =>
                {
                    b.Property<int>("SalonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SedeID")
                        .HasColumnType("int");

                    b.HasKey("SalonID");

                    b.HasIndex("SedeID");

                    b.ToTable("Salones", t =>
                        {
                            t.HasCheckConstraint("CK_Salon_Capacidad", "Capacidad > 0");
                        });
                });

            modelBuilder.Entity("Modelos.Models.Sede", b =>
                {
                    b.Property<int>("SedeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MunicipioID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SedeID");

                    b.HasIndex("MunicipioID");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Modelos.Models.SubcategoriaNecesidad", b =>
                {
                    b.Property<int>("SubcategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoriaID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubcategoriaID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("SubcategoriasNecesidades");
                });

            modelBuilder.Entity("Modelos.Models.UsuarioEstudiante", b =>
                {
                    b.Property<int>("UsuarioEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioEID"));

                    b.Property<byte[]>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoUsuarioEstadoID")
                        .HasColumnType("int");

                    b.Property<int>("Estudiante")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioEID");

                    b.HasIndex("Estado");

                    b.HasIndex("EstadoUsuarioEstadoID");

                    b.HasIndex("Estudiante");

                    b.HasIndex("EstudianteID");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("UsuariosEstudiantes");
                });

            modelBuilder.Entity("Modelos.Models.UsuarioPersonal", b =>
                {
                    b.Property<int>("UsuarioPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioPID"));

                    b.Property<byte[]>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoUsuarioEstadoID")
                        .HasColumnType("int");

                    b.Property<int>("Personal")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioPID");

                    b.HasIndex("Estado");

                    b.HasIndex("EstadoUsuarioEstadoID");

                    b.HasIndex("Personal");

                    b.HasIndex("PersonalID");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("UsuariosPersonal");
                });

            modelBuilder.Entity("ParticipantesEventos", b =>
                {
                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.HasKey("EstudianteID", "EventoID");

                    b.HasIndex("EventoID");

                    b.ToTable("ParticipantesEventos", (string)null);
                });

            modelBuilder.Entity("ProfesoresEstudiantes", b =>
                {
                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorID")
                        .HasColumnType("int");

                    b.HasKey("EstudianteID", "ProfesorID");

                    b.HasIndex("ProfesorID");

                    b.ToTable("ProfesoresEstudiantes", (string)null);
                });

            modelBuilder.Entity("ResponsablesEventos", b =>
                {
                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.HasKey("EventoID", "PersonalID");

                    b.HasIndex("PersonalID");

                    b.ToTable("ResponsablesEventos", (string)null);
                });

            modelBuilder.Entity("Modelos.Models.CartaGenerada", b =>
                {
                    b.HasOne("Modelos.Models.PlantillaCarta", "Plantilla")
                        .WithMany("CartasGeneradas")
                        .HasForeignKey("PlantillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.UsuarioPersonal", "UsuarioPersonal")
                        .WithMany("CartasGeneradas")
                        .HasForeignKey("UsuarioPersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantilla");

                    b.Navigation("UsuarioPersonal");
                });

            modelBuilder.Entity("Modelos.Models.Estudiante", b =>
                {
                    b.HasOne("Modelos.Models.Carrera", "CarreraNavigation")
                        .WithMany("Estudiantes")
                        .HasForeignKey("Carrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.DisciplinaArtistica", "DisciplinaNavigation")
                        .WithMany("Estudiantes")
                        .HasForeignKey("Disciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Municipio", "MunicipioNavigation")
                        .WithMany("Estudiantes")
                        .HasForeignKey("Municipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraNavigation");

                    b.Navigation("DisciplinaNavigation");

                    b.Navigation("MunicipioNavigation");
                });

            modelBuilder.Entity("Modelos.Models.Evento", b =>
                {
                    b.HasOne("Modelos.Models.Salon", "SalonNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("Salon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalonNavigation");
                });

            modelBuilder.Entity("Modelos.Models.Municipio", b =>
                {
                    b.HasOne("Modelos.Models.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Modelos.Models.NecesidadEvento", b =>
                {
                    b.HasOne("Modelos.Models.Evento", "Evento")
                        .WithMany("Necesidades")
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.SubcategoriaNecesidad", "Subcategoria")
                        .WithMany("NecesidadesEventos")
                        .HasForeignKey("SubcategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Modelos.Models.Personal", b =>
                {
                    b.HasOne("Modelos.Models.Cargo", "CargoNavigation")
                        .WithMany("Personales")
                        .HasForeignKey("Cargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.DisciplinaArtistica", "DisciplinaNavigation")
                        .WithMany("Personales")
                        .HasForeignKey("Disciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Municipio", "MunicipioNavigation")
                        .WithMany("Personales")
                        .HasForeignKey("Municipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoNavigation");

                    b.Navigation("DisciplinaNavigation");

                    b.Navigation("MunicipioNavigation");
                });

            modelBuilder.Entity("Modelos.Models.Salon", b =>
                {
                    b.HasOne("Modelos.Models.Sede", "Sede")
                        .WithMany("Salones")
                        .HasForeignKey("SedeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Modelos.Models.Sede", b =>
                {
                    b.HasOne("Modelos.Models.Municipio", "Municipio")
                        .WithMany("Sedes")
                        .HasForeignKey("MunicipioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Modelos.Models.SubcategoriaNecesidad", b =>
                {
                    b.HasOne("Modelos.Models.CategoriaNecesidad", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Modelos.Models.UsuarioEstudiante", b =>
                {
                    b.HasOne("Modelos.Models.EstadoUsuario", "EstadoNavigation")
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.EstadoUsuario", null)
                        .WithMany("UsuariosEstudiantes")
                        .HasForeignKey("EstadoUsuarioEstadoID");

                    b.HasOne("Modelos.Models.Estudiante", "EstudianteNavigation")
                        .WithMany()
                        .HasForeignKey("Estudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Estudiante", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("EstudianteID");

                    b.Navigation("EstadoNavigation");

                    b.Navigation("EstudianteNavigation");
                });

            modelBuilder.Entity("Modelos.Models.UsuarioPersonal", b =>
                {
                    b.HasOne("Modelos.Models.EstadoUsuario", "EstadoNavigation")
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.EstadoUsuario", null)
                        .WithMany("UsuariosPersonal")
                        .HasForeignKey("EstadoUsuarioEstadoID");

                    b.HasOne("Modelos.Models.Personal", "PersonalNavigation")
                        .WithMany()
                        .HasForeignKey("Personal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Personal", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonalID");

                    b.Navigation("EstadoNavigation");

                    b.Navigation("PersonalNavigation");
                });

            modelBuilder.Entity("ParticipantesEventos", b =>
                {
                    b.HasOne("Modelos.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfesoresEstudiantes", b =>
                {
                    b.HasOne("Modelos.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Profesor", null)
                        .WithMany()
                        .HasForeignKey("ProfesorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ResponsablesEventos", b =>
                {
                    b.HasOne("Modelos.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos.Models.Personal", null)
                        .WithMany()
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelos.Models.Cargo", b =>
                {
                    b.Navigation("Personales");
                });

            modelBuilder.Entity("Modelos.Models.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Modelos.Models.CategoriaNecesidad", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("Modelos.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("Modelos.Models.DisciplinaArtistica", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Personales");
                });

            modelBuilder.Entity("Modelos.Models.EstadoUsuario", b =>
                {
                    b.Navigation("UsuariosEstudiantes");

                    b.Navigation("UsuariosPersonal");
                });

            modelBuilder.Entity("Modelos.Models.Estudiante", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelos.Models.Evento", b =>
                {
                    b.Navigation("Necesidades");
                });

            modelBuilder.Entity("Modelos.Models.Municipio", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Personales");

                    b.Navigation("Sedes");
                });

            modelBuilder.Entity("Modelos.Models.Personal", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelos.Models.PlantillaCarta", b =>
                {
                    b.Navigation("CartasGeneradas");
                });

            modelBuilder.Entity("Modelos.Models.Salon", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Modelos.Models.Sede", b =>
                {
                    b.Navigation("Salones");
                });

            modelBuilder.Entity("Modelos.Models.SubcategoriaNecesidad", b =>
                {
                    b.Navigation("NecesidadesEventos");
                });

            modelBuilder.Entity("Modelos.Models.UsuarioPersonal", b =>
                {
                    b.Navigation("CartasGeneradas");
                });
#pragma warning restore 612, 618
        }
    }
}
